export type TechnologyTrack = {
  slug: string;
  title: string;
  image: string;
  duration: string;
  mode: string;
  level: string;
  track: string;
  overview: string;
  outcomes: string[];
};

export const technologyTracks: TechnologyTrack[] = [
  {
    slug: "php-development",
    title: "PHP Development",
    image: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?q=80&w=1200&auto=format&fit=crop",
    duration: "8 Weeks",
    mode: "Online/Offline",
    level: "Beginner to Intermediate",
    track: "Backend Development",
    overview: "Build dynamic websites and backend services using modern PHP practices, database design, and deployment workflows.",
    outcomes: ["Build CRUD applications", "Integrate MySQL securely", "Deploy production-ready PHP projects"],
  },
  {
    slug: "java-programming",
    title: "Java Programming",
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1200&auto=format&fit=crop",
    duration: "10 Weeks",
    mode: "Online/Offline",
    level: "Beginner to Advanced",
    track: "Core + Enterprise",
    overview: "Master Java from fundamentals to enterprise architecture patterns with project-led sessions and interview prep.",
    outcomes: ["Write robust OOP code", "Use collections and concurrency", "Build REST APIs with Java"],
  },
  {
    slug: "python-development",
    title: "Python Development",
    image: "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?q=80&w=1200&auto=format&fit=crop",
    duration: "8 Weeks",
    mode: "Online/Offline",
    level: "Beginner Friendly",
    track: "Automation and Data",
    overview: "Learn Python for automation, data workflows, and scripting by building hands-on projects from week one.",
    outcomes: ["Automate repetitive tasks", "Work with APIs and files", "Build data processing scripts"],
  },
  {
    slug: "dotnet-development",
    title: ".Net Development",
    image: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?q=80&w=1200&auto=format&fit=crop",
    duration: "10 Weeks",
    mode: "Online/Offline",
    level: "Intermediate",
    track: "App Development",
    overview: "Create modern applications with the .NET ecosystem, API services, and clean architecture principles.",
    outcomes: ["Develop C# applications", "Build .NET Web APIs", "Apply layered architecture"],
  },
  {
    slug: "angularjs-frontend",
    title: "AngularJS Frontend",
    image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?q=80&w=1200&auto=format&fit=crop",
    duration: "6 Weeks",
    mode: "Online/Offline",
    level: "Intermediate",
    track: "Frontend SPA",
    overview: "Build interactive single-page applications with Angular fundamentals, components, routing, and API integration.",
    outcomes: ["Design reusable components", "Manage routing and state", "Connect UI with backend APIs"],
  },
  {
    slug: "web-development",
    title: "Web Development",
    image: "https://images.unsplash.com/photo-1547658719-da2b51169166?q=80&w=1200&auto=format&fit=crop",
    duration: "12 Weeks",
    mode: "Online/Offline",
    level: "Beginner to Intermediate",
    track: "HTML CSS JS Stack",
    overview: "Start from fundamentals and build complete responsive websites with frontend best practices and project workflows.",
    outcomes: ["Create responsive layouts", "Write clean JavaScript", "Build portfolio-ready web projects"],
  },
  {
    slug: "palo-alto-security",
    title: "Palo Alto Security",
    image: "https://images.unsplash.com/photo-1562813733-b31f71025d54?q=80&w=1200&auto=format&fit=crop",
    duration: "6 Weeks",
    mode: "Online/Offline",
    level: "Intermediate to Advanced",
    track: "Network Security",
    overview: "Gain hands-on skills in policy design, threat prevention, and secure network architecture using Palo Alto firewalls.",
    outcomes: ["Configure security policies", "Implement threat controls", "Troubleshoot firewall environments"],
  },
  {
    slug: "check-point-firewall",
    title: "Check Point Firewall",
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=1200&auto=format&fit=crop",
    duration: "6 Weeks",
    mode: "Online/Offline",
    level: "Intermediate",
    track: "Enterprise Firewall",
    overview: "Learn enterprise-grade security gateway management with real scenarios in policy lifecycle and traffic inspection.",
    outcomes: ["Deploy firewall gateways", "Manage access control rules", "Apply security hardening steps"],
  },
  {
    slug: "cyber-security",
    title: "Cyber Security",
    image: "https://images.unsplash.com/photo-1510511459019-5dda7724fd87?q=80&w=1200&auto=format&fit=crop",
    duration: "12 Weeks",
    mode: "Online/Offline",
    level: "Beginner to Advanced",
    track: "SOC and Defense",
    overview: "Understand modern threats, incident response, and defensive security practices through practical cyber labs.",
    outcomes: ["Detect common attack vectors", "Perform incident triage", "Build secure defense workflows"],
  },
  {
    slug: "f5-big-ip",
    title: "F5 Big IP",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1200&auto=format&fit=crop",
    duration: "5 Weeks",
    mode: "Online/Offline",
    level: "Advanced",
    track: "ADC and Load Balancing",
    overview: "Specialize in traffic management, load balancing, and application delivery optimization with BIG-IP services.",
    outcomes: ["Configure virtual servers", "Set health monitors", "Optimize app delivery"],
  },
  {
    slug: "aws-cloud",
    title: "AWS Cloud",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1200&auto=format&fit=crop",
    duration: "8 Weeks",
    mode: "Online/Offline",
    level: "Beginner to Intermediate",
    track: "Cloud Practitioner",
    overview: "Build foundational to intermediate cloud skills with AWS services, architecture basics, and deployment pipelines.",
    outcomes: ["Design core cloud architecture", "Use EC2, S3, and IAM", "Prepare for cloud certification"],
  },
  {
    slug: "bgp-mpls",
    title: "BGP and MPLS",
    image: "https://images.unsplash.com/photo-1518773553398-650c184e0bb3?q=80&w=1200&auto=format&fit=crop",
    duration: "7 Weeks",
    mode: "Online/Offline",
    level: "Advanced",
    track: "Routing Specialist",
    overview: "Master advanced routing, carrier-grade networking, and troubleshooting patterns for service provider environments.",
    outcomes: ["Design BGP routing policies", "Understand MPLS VPN concepts", "Troubleshoot complex network paths"],
  },
];